// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ruqqpppvievpxmbnaxvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1cXFwcHB2aWV2cHhtYm5heHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzYzMDQsImV4cCI6MjA3MjIxMjMwNH0.QoS7kX1PWOYnArmVckyTS9C4r9kgSAgV1UpXxJpr8pU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});